function trashSelectedNote(){cancelLayout();const note=notes.find(n=>n.id===selected);if(!note)return;if(!confirm('Déplacer cette note dans la corbeille ?'))return;const p=activeMap();p.trash=p.trash||[];p.trash.push({id:crypto.randomUUID(),note:structuredClone(note),links:structuredClone(links.filter(e=>e.includes(note.id))),deletedAt:new Date().toISOString()});notes=notes.filter(n=>n.id!==note.id);links=links.filter(e=>!e.includes(note.id));selected=notes[0]?.id;editing=false;persist();draw();renderDetail();toast('Note déplacée dans la corbeille')}
function restoreNoteFromTrash(id){const p=activeMap(),record=(p.trash||[]).find(r=>r.id===id);if(!record)return;if(notes.some(n=>n.id===record.note.id)){toast('Cette note existe déjà');return}notes.push(structuredClone(record.note));for(const e of record.links||[]){if(notes.some(n=>n.id===e[0])&&notes.some(n=>n.id===e[1])&&!links.some(l=>l.includes(e[0])&&l.includes(e[1])))links.push(e)}p.trash=p.trash.filter(r=>r.id!==id);selected=record.note.id;filter='all';persist();draw();renderDetail();renderRecovery();toast('Note restaurée avec ses liens disponibles')}
function restoreArchivedProject(id){const archived=workspace.archivedProjects||[],p=archived.find(p=>p.id===id);if(!p)return;workspace.archivedProjects=archived.filter(p=>p!==p);delete p.deletedAt;if(workspace.projects.some(v=>v.id===p.id))p.id='project-'+crypto.randomUUID();workspace.projects.push(p);switchProject(p.id);saveWorkspace();renderRecovery();toast('Projet restauré')}
function updateTrashCount(){const el=document.getElementById('trash-count');if(el)el.textContent=(activeMap().trash||[]).length+(workspace.archivedProjects||[]).length}
function renderRecovery(){const host=document.getElementById('recovery-content');host.innerHTML=`<h3>Notes supprimées · ${escapeHtml(activeProject().name)}</h3>`+(activeMap().trash||[]).map(r=>`<div class="recovery-row"><div><strong>${escapeHtml(r.note.title)}</strong><small>${escapeHtml(new Date(r.deletedAt).toLocaleString('fr-FR'))}</small></div><button class="share" data-restore-note="${escapeHtml(r.id)}">Restaurer</button></div>`).join('')+(!(activeMap().trash||[]).length?'<p>Aucune note supprimée dans ce projet.</p>':'')+'<h3>Projets supprimés</h3>'+(workspace.archivedProjects||[]).map(p=>`<div class="recovery-row"><div><strong>${escapeHtml(p.name)}</strong><small>${p.notes.length} notes</small></div><button class="share" data-restore-project="${escapeHtml(p.id)}">Restaurer</button></div>`).join('')+(!(workspace.archivedProjects||[]).length?'<p>Aucun projet supprimé.</p>':'');host.querySelectorAll('[data-restore-note]').forEach(b=>b.onclick=()=>restoreNoteFromTrash(b.dataset.restoreNote));host.querySelectorAll('[data-restore-project]').forEach(b=>b.onclick=()=>restoreArchivedProject(b.dataset.restoreProject));updateTrashCount()}
function renderBacklinks(note){const found=notes.filter(n=>n.id!==note.id&&wikiTitles(n.body).some(title=>title.toLocaleLowerCase()===note.title.trim().toLocaleLowerCase()));return `<div class="link-section"><div class="link-heading">Mentions entrantes <small>${found.length}</small></div>`+(found.length?found.map(n=>`<button class="linked-note" data-linked="${escapeHtml(n.id)}">↳ ${escapeHtml(n.title)}</button>`).join(''):'<p class="backlink-empty">Aucune autre note ne mentionne encore celle-ci.</p>')+'</div>'}
function wikiTitles(body){return [...body.replace(/```[\s\S]*?(?:```|$)/g,'').replace(/`[^`\n]*`/g,'').matchAll(/\[\[([^\]]+)\]\]/g)].map(m=>m[1].trim())}
function renameNoteReferences(oldTitle,newTitle,id){if(oldTitle===newTitle||notes.some(n=>n.id!==id&&n.title.toLocaleLowerCase()===newTitle.toLocaleLowerCase())||notes.filter(n=>n.title.toLocaleLowerCase()===oldTitle.toLocaleLowerCase()).length!==1)return;for(const n of notes){if(n.id===id)continue;n.body=n.body.replace(/```[\s\S]*?(?:```|$)|`[^`\n]*`|\[\[([^\]]+)\]\]/g,(whole,title)=>title&&title.trim().toLocaleLowerCase()===oldTitle.trim().toLocaleLowerCase()?'[['+newTitle+']]':whole)}}
function toggleWritingMode(){const writing=document.querySelector('.app').classList.toggle('writing-mode');const b=document.getElementById('writing-mode');b.textContent=writing?'Graphe':'Écrire';b.setAttribute('aria-pressed',String(writing));if(writing&&selected){editing=true;renderDetail();document.getElementById('editor-body')?.focus()}requestAnimationFrame(draw)}
function sanitizeImportedTrash(items, terminal=false){if(!Array.isArray(items))return [];return items.map(r=>{if(!r||!r.note)return null;try{const note=validateImportedProject({notes:[r.note]},terminal?1:0).notes[0];return {id:crypto.randomUUID(),note,links:Array.isArray(r.links)?r.links.filter(e=>Array.isArray(e)&&typeof e[0]==='string'&&typeof e[1]==='string'):[],deletedAt:typeof r.deletedAt==='string'?r.deletedAt:new Date().toISOString()}}catch{return null}}).filter(Boolean)}
function initializeRecovery(){document.getElementById('open-trash').onclick=()=>{renderRecovery();document.getElementById('recovery-dialog').showModal()};document.getElementById('import-markdown').onclick=chooseMarkdownFiles;document.getElementById('writing-mode').onclick=toggleWritingMode;updateTrashCount()}
