// Document navigation and graph navigation share the same saved notes.
var documentMode=localStorage.getItem('cosmos-display-mode')!=='graph';
let sidebarWidth=Number(localStorage.getItem('cosmos-sidebar-width'))||280;
const dirtyDatabases=new Set();const frCollator=new Intl.Collator('fr',{sensitivity:'base',numeric:true});const sortedEntryCache=new WeakMap();
let editorSaveTimer=null,editorPreviewTimer=null,editorDirty=false;
let sidebarTerm='',sidebarPage=0,documentFolder='',navigationCache=null;
function scheduleEditorSave(note){if(note.notion?.kind==='database')dirtyDatabases.add(note);editorDirty=true;clearTimeout(editorSaveTimer);editorSaveTimer=setTimeout(flushEditorSave,1200);clearTimeout(editorPreviewTimer);editorPreviewTimer=setTimeout(()=>{const preview=document.getElementById('live-preview');if(preview&&notes.find(n=>n.id===selected)===note)preview.innerHTML=note.notion?.kind==='database'?'':renderMarkdown(note.body,false)},180);document.querySelector('.save-state').textContent='Modifications en cours…'}
function flushEditorSave(){clearTimeout(editorSaveTimer);if(!editorDirty)return;editorDirty=false;for(const n of dirtyDatabases)n.body=databaseMarkdown(n.notion);dirtyDatabases.clear();syncWikiLinks();saveWorkspace();document.querySelector('.save-state').textContent='Enregistrement…'}
window.addEventListener('pagehide',flushEditorSave);
window.addEventListener('blur',flushEditorSave);
function invalidateNavigation(){navigationCache=null}
function projectDocuments(){const p=activeProject();const signature=p.notes.length+':'+p.notes.reduce((s,n)=>s+(n.starMap?.notes.length||0),0);if(navigationCache?.project===p&&navigationCache.signature===signature)return navigationCache;
 const entries=p.notes.flatMap(n=>[{note:n,galaxy:null},...(n.starMap?.notes||[]).map(note=>({note,galaxy:n.id}))]);const byId=new Map(entries.map(e=>[e.note.id,e])),byTitle=new Map();for(const e of entries){const key=e.note.title.toLocaleLowerCase();if(!byTitle.has(key))byTitle.set(key,[]);byTitle.get(key).push(e)}
 // URL indexes are only needed to follow imported links: build them on first use.
 let urls=null;const buildUrls=()=>{if(urls)return urls;const byUrl=new Map(),byNotionId=new Map();for(const e of entries){const n=e.note;if(!n.notion?.source)continue;const url=notionUrl(n.notion.source,'',n.notion.root);byUrl.set(url,e);for(const alias of n.notion.alternateSources||[])byUrl.set(notionUrl(alias.source,'',alias.root),e);byUrl.set(url.replace(/\.(html|md)$/,(_,ext)=>ext==='html'?'.md':'.html'),e);if(url.endsWith('_all.csv'))byUrl.set(url.replace(/_all\.csv$/,'.csv'),e);const id=n.notion.source.match(/([a-f\d]{32})(?:_all)?\.[^.]+$/i)?.[1];if(id)byNotionId.set(id,e)}return urls={byUrl,byNotionId}};
 return navigationCache={project:p,signature,entries,byId,byTitle,get byUrl(){return buildUrls().byUrl},get byNotionId(){return buildUrls().byNotionId}};}
function openDocument(id){const entry=projectDocuments().byId.get(id);if(!entry)return;if(editing)captureEditor();flushEditorSave();cancelLayout();saveWorkspace();currentGalaxyId=entry.galaxy;const map=activeMap();notes=map.notes;links=map.links;selected=id;editing=false;filter='all';query='';renderProjectUI();draw();renderDetail();document.querySelector('.detail').scrollTop=0}
function setDisplayMode(mode){if(editing)captureEditor();flushEditorSave();documentMode=mode==='documents';localStorage.setItem('cosmos-display-mode',documentMode?'documents':'graph');document.getElementById('primary-nav-label').textContent=documentMode?'Toutes les pages':'Graphe global';document.querySelector('.app').classList.toggle('document-mode',documentMode);document.querySelector('.app').classList.remove('writing-mode');editing=false;document.querySelectorAll('[data-display-mode]').forEach(b=>{b.classList.toggle('active',b.dataset.displayMode===mode);b.setAttribute('aria-pressed',String(b.dataset.displayMode===mode))});document.getElementById('writing-mode').textContent='Écrire';renderProjectNotes();draw();renderDetail()}
function setSidebarWidth(width){sidebarWidth=Math.max(200,Math.min(Math.min(600,window.innerWidth-450),width));document.documentElement.style.setProperty('--sidebar-width',sidebarWidth+'px');document.getElementById('sidebar-resizer')?.setAttribute('aria-valuenow',String(Math.round(sidebarWidth)))}
const legacyProjectNotes=renderProjectNotes;
renderProjectNotes=function(){const host=document.getElementById('project-notes');if(!host)return;const data=projectDocuments();let entries=documentMode?data.entries:notes.map(note=>({note}));const term=sidebarTerm.toLocaleLowerCase();
 if(term)entries=entries.filter(e=>e.note.title.toLocaleLowerCase().includes(term)||String(e.note.notion?.source||'').toLocaleLowerCase().includes(term));
 else if(documentMode&&filter==='all'){entries=entries.filter(e=>{const source=e.note.notion?.source;return source?source.split('/').slice(1,-1).join('/')===documentFolder:!documentFolder})}
 if(filter==='favorites')entries=entries.filter(e=>e.note.favorite);else if(['Idées','Recherche','Projets','Journal'].includes(filter))entries=entries.filter(e=>e.note.group===filter);else if(filter==='recent')entries=entries.sort((a,b)=>String(b.note.updatedAt||'').localeCompare(String(a.note.updatedAt||''))).slice(0,30);
 const directories=new Set();if(documentMode&&!term&&filter==='all')for(const e of data.entries){const parts=e.note.notion?.source?.split('/').slice(1,-1)||[];const dir=parts.join('/');if(dir&&(!documentFolder||dir.startsWith(documentFolder+'/'))){const rest=documentFolder?dir.slice(documentFolder.length+1):dir;if(rest)directories.add(rest.split('/')[0])}}
 if(filter!=='recent'){const ck=[activeProjectId,currentGalaxyId,documentMode,documentFolder,filter,term,notes.length,entries.length].join('|');let bucket=null;if(filter!=='favorites'){bucket=sortedEntryCache.get(data);if(!bucket)sortedEntryCache.set(data,bucket=new Map())}const hit=bucket?.get(ck);if(hit)entries=hit;else{entries.sort((a,b)=>frCollator.compare(a.note.title,b.note.title));bucket?.set(ck,entries)}}const total=entries.length;sidebarPage=Math.max(0,Math.min(sidebarPage,Math.ceil(total/80)-1));const visible=entries.slice(sidebarPage*80,sidebarPage*80+80);
 const key=JSON.stringify([activeProjectId,currentGalaxyId,selected,documentMode,documentFolder,filter,term,sidebarPage,[...directories],visible.map(e=>[e.note.id,e.note.title])]);if(host.dataset.renderKey===key)return;host.dataset.renderKey=key;
 host.innerHTML=(documentMode&&!term&&documentFolder?'<button class="project-note" data-parent>← Dossier parent</button>':'')+[...directories].sort().map(dir=>`<button class="project-note directory" data-dir="${escapeHtml(dir)}">▸ <span>${escapeHtml(cleanNotionTitle(dir))}</span></button>`).join('')+visible.map(({note:n})=>`<button title="${escapeHtml(n.notion?.source||n.title)}" class="project-note ${n.id===selected?'selected':''}" data-document="${n.id}"><span class="page-icon">${n.notion?.kind==='database'?'▦':'▤'}</span><span>${escapeHtml(n.title)}</span></button>`).join('')+`<div class="sidebar-pages"><button data-page="-1" ${sidebarPage===0?'disabled':''}>←</button><span>${total?sidebarPage*80+1:0}–${Math.min(total,(sidebarPage+1)*80)} / ${total}</span><button data-page="1" ${(sidebarPage+1)*80>=total?'disabled':''}>→</button></div>`;
 host.querySelectorAll('[data-document]').forEach(b=>b.onclick=()=>documentMode?openDocument(b.dataset.document):select(b.dataset.document));host.querySelectorAll('[data-dir]').forEach(b=>b.onclick=()=>{documentFolder=[documentFolder,b.dataset.dir].filter(Boolean).join('/');sidebarPage=0;renderProjectNotes()});host.querySelector('[data-parent]')?.addEventListener('click',()=>{documentFolder=documentFolder.split('/').slice(0,-1).join('/');sidebarPage=0;renderProjectNotes()});host.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{sidebarPage+=Number(b.dataset.page);renderProjectNotes()});
};
// Wiki link scans are linear and cached by body, rather than repeatedly parsing all pages.
const wikiCache=new WeakMap();
wikiTitles=function(body){return [...String(body).replace(/```[\s\S]*?(?:```|$)/g,'').replace(/`[^`\n]*`/g,'').matchAll(/\[\[([^\]]+)\]\]/g)].map(m=>m[1].trim())};
function cachedWiki(n){let entry=wikiCache.get(n);if(!entry||entry.body!==n.body){entry={body:n.body,titles:wikiTitles(n.body)};wikiCache.set(n,entry)}return entry.titles}
syncWikiLinks=function(){const titles=new Map(notes.map(n=>[n.title.trim().toLocaleLowerCase(),n]));links=links.filter(e=>e[2]!=='wiki');const keys=new Set(links.map(e=>[e[0],e[1]].sort().join(':')));for(const n of notes)for(const title of cachedWiki(n)){const target=titles.get(title.toLocaleLowerCase());if(!target||target.id===n.id)continue;const key=[n.id,target.id].sort().join(':');if(!keys.has(key)){keys.add(key);links.push([n.id,target.id,'wiki'])}}};
renderBacklinks=function(note){const found=notes.filter(n=>n.id!==note.id&&cachedWiki(n).some(t=>t.toLocaleLowerCase()===note.title.trim().toLocaleLowerCase()));return '<details class="link-section"><summary>Mentions entrantes · '+found.length+'</summary>'+found.slice(0,100).map(n=>`<button class="linked-note" data-linked="${n.id}">${escapeHtml(n.title)}</button>`).join('')+'</details>'};
const oldToggleWriting=toggleWritingMode;
toggleWritingMode=function(){if(editing){saveEdit();return}editing=true;renderDetail();document.getElementById('editor-body')?.focus()};
const baseDetail=renderDetail;
renderDetail=function(){baseDetail();document.getElementById('writing-mode').textContent=editing?'Terminer':'Écrire';const n=notes.find(n=>n.id===selected);if(!n)return;const box=document.getElementById('detail-content');if(documentMode){const crumb=document.createElement('div');crumb.className='document-breadcrumb';crumb.textContent=n.notion?.source?.split('/').slice(1,-1).map(cleanNotionTitle).join(' / ')||activeProject().name;box.prepend(crumb);box.querySelectorAll('div.link-section').forEach(section=>{const folded=document.createElement('details');folded.className='link-section';const summary=document.createElement('summary');summary.textContent='Notes liées';folded.append(summary,...section.childNodes);section.replaceWith(folded)})}
 box.querySelectorAll('[data-notion-url]').forEach(a=>a.onclick=e=>{const data=projectDocuments(),url=a.dataset.notionUrl;const match=data.byUrl.get(url.split('#')[0])||(/https?:\/\/(?:www\.|app\.)?notion\.(?:so|com)\//.test(url)?data.byNotionId.get(url.replaceAll('-','').match(/[a-f\d]{32}/i)?.[0]):null);if(match){e.preventDefault();openDocument(match.note.id)}});
};
searchRender=function(q){const host=document.getElementById('search-results'),term=q.toLocaleLowerCase();const found=projectDocuments().entries.filter(({note:n})=>!term||n.title.toLocaleLowerCase().includes(term)||n.body.toLocaleLowerCase().includes(term)).slice(0,30);host.innerHTML=found.map(({note:n})=>`<button class="result" data-id="${n.id}"><span>${escapeHtml(n.title)}</span></button>`).join('')||'<p>Aucune note trouvée</p>';host.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>{openDocument(b.dataset.id);document.getElementById('search-overlay').classList.remove('open')})};
(function initializeDocumentUI(){const app=document.querySelector('.app');const modes=document.createElement('div');modes.className='display-modes';modes.innerHTML='<button data-display-mode="documents">▤ Documents</button><button data-display-mode="graph">✧ Graphe</button>';document.querySelector('.topbar').prepend(modes);modes.querySelectorAll('button').forEach(b=>b.onclick=()=>setDisplayMode(b.dataset.displayMode));const search=document.createElement('input');search.id='sidebar-search';search.type='search';search.placeholder='Rechercher une page…';search.setAttribute('aria-label','Rechercher dans toutes les pages');search.oninput=()=>{sidebarTerm=search.value;sidebarPage=0;renderProjectNotes()};document.getElementById('project-notes').before(search);
 const handle=document.createElement('div');handle.id='sidebar-resizer';handle.setAttribute('role','separator');handle.tabIndex=0;handle.setAttribute('aria-label','Largeur du panneau gauche');handle.setAttribute('aria-orientation','vertical');handle.setAttribute('aria-valuemin','200');handle.setAttribute('aria-valuemax','600');app.append(handle);handle.onpointerdown=e=>{handle.setPointerCapture(e.pointerId);handle.dataset.dragging='true';document.body.classList.add('resizing-sidebar')};handle.onpointermove=e=>{if(handle.dataset.dragging)setSidebarWidth(e.clientX)};const finish=()=>{delete handle.dataset.dragging;document.body.classList.remove('resizing-sidebar');localStorage.setItem('cosmos-sidebar-width',String(sidebarWidth));if(!documentMode)draw()};handle.onpointerup=finish;handle.onpointercancel=finish;handle.onkeydown=e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();setSidebarWidth(sidebarWidth+(e.key==='ArrowRight'?20:-20));finish()}};setSidebarWidth(sidebarWidth);document.getElementById('writing-mode').onclick=toggleWritingMode;setDisplayMode(documentMode?'documents':'graph');})();

function databaseRowPage(database,row){const data=projectDocuments();const title=String(row[database.notion.columns[0]]||'').trim().toLocaleLowerCase();const candidates=data.byTitle.get(title)||[];const prefix=database.notion.source.replace(/\s+[a-f\d]{32}(?:_all)?\.csv$/i,'')+'/';const inside=candidates.filter(e=>e.note.id!==database.id&&e.note.notion?.source.startsWith(prefix));return inside.length===1?inside[0]:candidates.length===1&&candidates[0].note.id!==database.id?candidates[0]:null}
function sanitizedSource(html,path,root){const doc=new DOMParser().parseFromString(html,'text/html');doc.querySelectorAll('script,style,iframe,object,embed,form,input,button,link,meta,base,svg,math').forEach(e=>e.remove());const allowed=new Set(['P','DIV','SPAN','ARTICLE','SECTION','HEADER','FOOTER','H1','H2','H3','H4','H5','H6','UL','OL','LI','TABLE','THEAD','TBODY','TR','TD','TH','FIGURE','FIGCAPTION','BLOCKQUOTE','PRE','CODE','STRONG','B','EM','I','S','DEL','U','A','IMG','BR','HR','DETAILS','SUMMARY']);for(const el of [...doc.body.querySelectorAll('*')]){if(!allowed.has(el.tagName)){el.replaceWith(...el.childNodes);continue}const src=el.getAttribute('src'),href=el.getAttribute('href');for(const attr of [...el.attributes])el.removeAttribute(attr.name);if(el.tagName==='IMG'&&src)el.setAttribute('src',notionUrl(src,path,root));if(el.tagName==='A'&&href)el.setAttribute('href',notionUrl(href,path,root))}return '<!doctype html><meta charset="utf-8"><style>body{font:15px/1.7 system-ui;color:#dbe5f5;background:#111b2d;padding:20px}img{max-width:100%;height:auto}a{color:#a4baff}table{border-collapse:collapse;display:block;overflow:auto}td,th{border:1px solid #45546a;padding:8px}pre{white-space:pre-wrap}</style>'+doc.body.innerHTML}
const detailWithSource=renderDetail;
renderDetail=function(){detailWithSource();const n=notes.find(n=>n.id===selected);if(!n?.notion||n.notion.kind==='database'||!nativeStore?.readImportFile)return;const details=document.createElement('details');details.className='source-preview';details.innerHTML='<summary>Consulter le document source</summary>';let loaded=false;details.ontoggle=()=>{if(!details.open||loaded)return;loaded=true;const source=(n.notion.alternateSources||[]).find(s=>/\.html?$/i.test(s.source))||n.notion;nativeStore.readImportFile(notionUrl(source.source,'',source.root),text=>{if(!text){const p=document.createElement('p');p.textContent='Source indisponible dans ce coffre. Le contenu importé reste accessible ci-dessus.';details.append(p);return}if(/\.html?$/i.test(source.source)){const frame=document.createElement('iframe');frame.title='Document HTML d’origine';frame.setAttribute('sandbox','');frame.srcdoc=sanitizedSource(text,source.source,source.root);details.append(frame)}else{const pre=document.createElement('pre');pre.textContent=text;details.append(pre)}})};document.getElementById('detail-content').append(details)};

const mapCounts=updateCounts;
updateCounts=function(){mapCounts();if(!documentMode)return;const all=projectDocuments().entries.map(e=>e.note);document.getElementById('note-count').textContent=all.length;document.querySelector('.storage-head strong').textContent=all.length.toLocaleString('fr-FR')+' pages';document.querySelector('[data-view="Favoris"] .nav-count').textContent=all.filter(n=>n.favorite).length;};
