(async()=>{try{
 const check=(v,m)=>{if(!v)throw Error(m)};
 for(let attempt=0;!nativeHydrated&&attempt<100;attempt++)await new Promise(resolve=>setTimeout(resolve,100));check(nativeHydrated,'native storage ready');
 const parsed=csvTable('\uFEFFName,Status,Text,Empty\r\n"A, B",Todo,"first\nsecond ""quoted""",\r\nC,Done,x,');
 check(parsed.rows.length===2&&parsed.columns.length===4&&parsed.rows[0].Text==='first\nsecond "quoted"','quoted multiline CSV');
 check(csvTable('Name,Empty\n').columns.length===2,'empty database headers');
 const fixture={root:'/tmp',pages:[{path:'Export/Home aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.html',title:'Home',kind:'html',html:'<h1>Home</h1><h2>Section</h2><p><strong>Bold</strong></p><img src="Home/a%20b.png"><script>window.attacked=true</script>'},{path:'Export/Home/Tasks bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb.csv',title:'Tasks bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',kind:'csv',html:'Name,Status\nFirst,Todo\nSecond,Done'},{path:'Export/Home/one.md',title:'Same',kind:'markdown',html:'# First'},{path:'Export/Home/two.md',title:'Same',kind:'markdown',html:'# Second'},{path:'Export/Unrelated/lost.md',title:'Lost',kind:'markdown',html:'Preserved'}]};
 const result=buildNotionProject(fixture);check(result.notes[0].starMap.notes.length===3,'hierarchy without IDs and duplicate titles');check(result.notes[1].starMap.notes.length===1,'orphan preserved');check(result.notes[0].body.includes('## Section')&&result.notes[0].body.includes('**Bold**'),'HTML structure');check(result.notes[0].body.includes('file:///tmp/Export/Home/a%20b.png'),'image root');check(!result.notes[0].body.includes('attacked'),'scripts stripped');
 const md=buildNotionProject({root:'/tmp',pages:[{path:'note.md',title:'Note',kind:'markdown',html:'# Hello'}]});check(md.notes[0].body==='# Hello','Markdown-only archive');
 await importNotionWorkspace(fixture);openGalaxy(notes[0].id);const db=notes.find(n=>n.notion.kind==='database');select(db.id);
 check(document.querySelectorAll('.notion-table tbody tr').length===2,'table shown');const cell=document.querySelector('.notion-table textarea');cell.value='Edited';cell.dispatchEvent(new Event('input'));check(db.notion.rows[0].Name==='Edited','cell updates');
 document.querySelector('[data-view="kanban"]').click();check(document.querySelectorAll('.notion-kanban article').length===2,'one card per row');check(!document.querySelector('.notion-table'),'exclusive views');
 const status=document.querySelector('.notion-kanban [data-key="1"]');status.value='Done';status.dispatchEvent(new Event('input'));status.dispatchEvent(new Event('change'));check(document.querySelectorAll('.notion-kanban section').length===1,'Kanban regroup');
 const restored=validateImportedProject(JSON.parse(JSON.stringify(activeProject())));check(restored.notes[0].starMap.notes[0].notion.rows[0].Name==='Edited','backup retains database edits');
 document.querySelector('[data-add]').click();check(db.notion.rows.length===3,'add row');
 db.notion.rows=Array.from({length:205},(_,i)=>({Name:'Row '+i,Status:'Todo'}));db.notion.view='table';renderDetail();document.querySelector('[data-next]').click();document.querySelector('[data-next]').click();check(document.querySelectorAll('.notion-table tbody tr').length===5,'all rows reachable');
 select(notes.find(n=>n.notion.kind==='document').id);editing=true;renderDetail();check(document.querySelector('.editor-toolbar')&&document.querySelector('.preview').open,'writing tools');
 const tableHtml=renderMarkdown('| A | B |\n| --- | --- |\n| x | y |');check(tableHtml.includes('<table'),'Markdown tables');check(!renderMarkdown('[bad](javascript:alert) <img src=x onerror=alert(1)>').includes('<img'),'inert markdown');
 const countBefore=workspace.projects.length;const cancelJob=importNotionWorkspace({root:'/tmp',pages:Array.from({length:100},(_,i)=>({path:'page'+i+'.md',title:'Page '+i,html:'# Page',kind:'markdown'}))});document.querySelector('.import-progress button').click();await cancelJob;check(workspace.projects.length===countBefore,'cancel adds no project');
 let report='PASS: CSV multiligne, hiérarchie, homonymes, Markdown seul, images, sécurité, édition, Kanban, pagination et restauration JSON';
 if(window.notionFixture){const start=performance.now();let ticks=0;const heartbeat=setInterval(()=>ticks++,20);const real=await importNotionWorkspace(window.notionFixture);clearInterval(heartbeat);check(ticks>1,'import yields to UI');const all=real.notes.flatMap(n=>[n,...(n.starMap?.notes||[])]).filter(n=>n.notion);if(window.notionFixture.combined){const sources=new Set(all.flatMap(n=>[{source:n.notion.source,root:n.notion.root},...(n.notion.alternateSources||[])]).map(s=>s.root+'/'+s.source));check(window.notionFixture.pages.every(p=>sources.has((p.assetRoot||window.notionFixture.root)+'/'+p.path)),'all merged source documents retained');check(all.length<window.notionFixture.pages.length,'combined exports deduplicated')}else check(all.length===window.notionFixture.pages.length,'all archive documents retained');check(new Set(all.map(n=>n.notion.source)).size===all.length,'unique source documents');const databases=all.filter(n=>n.notion.kind==='database');check(window.notionFixture.combined?databases.length>=32:databases.length===window.notionFixture.pages.filter(p=>p.kind==='csv').length,'all CSV databases');const roundtrip=validateImportedProject(JSON.parse(JSON.stringify(real)));check(roundtrip.notes.length===real.notes.length,'full export restoration');const images=all.flatMap(n=>[...n.body.matchAll(/!\[[^\]]*\]\((file:[^)]+)\)/g)].map(m=>m[1]));window.cosmosNotionAssets=images;check(images.length>500,'local images retained: '+images.length);
 if(window.notionFixture.pages.some(p=>p.kind==='html')){const sample=window.notionFixture.pages.find(p=>p.path.endsWith('/Artline 28426fe1f8d680caa8faf0d767801423.html'));const imageUrl=notionUrl('Artline/tlchargement.png',sample.path,sample.assetRoot||window.notionFixture.root);const loaded=await new Promise(resolve=>{const img=new Image();img.onload=()=>resolve(img.naturalWidth>0);img.onerror=()=>resolve(false);img.src=imageUrl;setTimeout(()=>resolve(false),5000)});check(loaded,'real local image loads in Qt');}report+='; archive réelle : '+all.length+' documents, '+databases.length+' CSV, '+images.length+' références images, '+Math.round((performance.now()-start)/1000)+' s';
 // Render a representative real database without touching the user's vault.
 activeProjectId=real.id;currentGalaxyId=null;notes=real.notes;links=real.links;const owner=real.notes.find(n=>n.starMap?.notes.some(s=>s.notion?.kind==='database'));if(owner){openGalaxy(owner.id);select(notes.find(n=>n.notion?.kind==='database').id);setDisplayMode('documents');editing=false;renderDetail()}
 }
 setDisplayMode('documents');check(document.querySelector('.app').classList.contains('document-mode')&&!editing,'document mode independent of editing');setSidebarWidth(420);check(sidebarWidth===420,'sidebar resize');setSidebarWidth(280);
 const doc=projectDocuments().entries.find(e=>e.note.notion?.kind==='document'||e.note.notion?.kind==='page');if(doc){openDocument(doc.note.id);editing=true;renderDetail();const area=document.getElementById('editor-body');const before=area.value;const start=performance.now();for(let i=0;i<100;i++){area.value=before+' '+i;area.dispatchEvent(new Event('input',{bubbles:true}))}const elapsed=performance.now()-start;check(elapsed<1000,'typing 100 characters <1s: '+elapsed);area.value=before;captureEditor();saveEdit();report+='; 100 frappes : '+Math.round(elapsed)+' ms';}
 check(document.querySelectorAll('#project-notes [data-document]').length<=80,'sidebar bounded');
 const nested=renderMarkdown('- Parent\n  - Child\n\nhttps://example.com');check(nested.includes('<ul>\n<li>Child'),'nested lists');
 setDisplayMode('graph');check(!document.querySelector('.app').classList.contains('document-mode'),'graph mode');check(document.querySelectorAll('#graph .node').length<=350,'bounded graph');setDisplayMode('documents');
 const databaseEntry=projectDocuments().entries.find(e=>e.note.notion?.kind==='database'&&e.note.notion.rows.length>5);if(databaseEntry){openDocument(databaseEntry.note.id);databaseEntry.note.notion.view='kanban';renderDetail();const columns=databaseEntry.note.notion.columns;const row=databaseEntry.note.notion.rows.find(r=>databaseRowPage(databaseEntry.note,r));if(row){const target=databaseRowPage(databaseEntry.note,row);check(projectDocuments().byId.has(target.note.id),'database row opens existing page')}}
 window.cosmosNotionResult=report;
}catch(e){window.cosmosNotionResult='FAIL: '+e.stack}})();
